language: node_js

node_js:
- 12

cache:
 npm: false

install:
- npm install

script:
- npm run lint
- npm run build
- npm test
- travis_retry npm run e2e

deploy:
 provider: heroku
 app: ngx-crud-playground
 api_key:
  secure: "C7if3IJBM+WRTQQzXcwwkbYGQQYjDtC3XFs4wPDbsqBFokdUa12NF/evgxUDphPrDgA54BvK6w7bSsORgWIe0Hxg/QWWTYcunAZc14ok092fgmcMeSWQ2VrTZdByuu473LZf8aFIu6iUEdZBgOtPiWMuw7v1iW7gXgNdnPeqwSLMXZOEOdo3/0AuEgLhE77kROQtuQ6CyKVeJuz1kY8JoqtLNMex3/5/IHgB8TQ3V/Xht4xtXvMMJ4XziWsDBmv6hpA4mc/rx3Nf7Hhb7Vz8liPPH6lrY7fstOglOTX+EjvnChCS2yWKBqXfdVAI9YqXC2vz1OVfiRi5yRBIehXrWMO6J8GPGie88wXSjbauc50F4/GR8DBxT49H8FwjZ9PkhPLr9jsxf0p2Q0dOJbgXexhoOuqt7hqzzZ3NcPiqW/yILnRIhahSDYJ/0G3dBZdQ9IvvgqASWPi4MEh2k12adcooPw1mvbAS7IfMOupcNzlEWBD19qjpPWEdYh19+FermoNxGK8i5DZdYn5LZfDIw6uyMoJv+sb3idSnl5iRwtJfIbGPdsRkKSrCHuUnP+8EwkjWRnhW4qz0y/28C0NSJDVAMLJD3kDaA6kJuHEvS0exqfbSUUuwPid0xCyGg26OzDSY+rJwk1XCc2UmtkFtfCGpa+4WwgX6QE2M7jj6xAQ=
