name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 14
    uses: actions/setup-node@v1
    with:
     node-version: 14
  - run: npm install
  - run: npm run lint
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 14
    uses: actions/setup-node@v1
    with:
     node-version: 14
  - run: npm install
  - run: npm run build
 test-unit:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 14
    uses: actions/setup-node@v1
    with:
     node-version: 14
  - run: npm install
  - run: npm run test
 test-acceptance:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Node 14
    uses: actions/setup-node@v1
    with:
     node-version: 14
  - run: npm install
  - run: npm run e2e
 deploy:
  needs: [ build, test-unit, test-acceptance ]
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Deploy to Heroku
    uses: akhileshns/heroku-deploy@v3.6.8
    with:
     heroku_app_name: ngx-crud-playground
     heroku_email: info@redaxmedia.com
     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
